### ISSUE TITLE
Bookmark tab

### ISSUE THREAD

**Issue by Rezert-g** [balvinderz/animewatcher#11]
So i just downloaded the app and its amazing but i was just wondering if at all possible you would be able to add a bookmarks tab so we dont have to search it up each time. Its not that important but it would be great if you could add this feature

**Comment by balvinderz** [comment]
Sorry I dont have time for any new features right now. I just update the scrapers so the app works . I will accept pr if anyone else wants to add it in this app .

**Comment by Rezert-g** [comment]
> Sorry I dont have time for any new features right now. I just update the scrapers so the app works . I will accept pr if anyone else wants to add it in this app .

Ok thanks for letting me know
