### ISSUE TITLE
download 

### ISSUE THREAD

**Issue by Rezert-g** [balvinderz/animewatcher#12]
I don't know where to download this streaming platform I can't find a button at all that lets me download

**Comment by yugalkukde** [comment]
[here you go](https://github.com/balvinderz/animewatcher/releases/download/1.0.0/app-release.apk) bro

**Comment by Rezert-g** [comment]
> [here you go](https://github.com/balvinderz/animewatcher/releases/download/1.0.0/app-release.apk) bro

I appreciate it. just making sure this is up to date

**Comment by balvinderz** [comment]
its up to date.  thank you @bangyboost  for addressing @Rezert-g  issue. Should i close this now?

**Comment by Rezert-g** [comment]
> its up to date.  thank you @bangyboost  for addressing @Rezert-g  issue. Should i close this now? 

yea thanks
