### ISSUE TITLE
Anime List Not Working ..!

### ISSUE THREAD

**Issue by Norman191** [balvinderz/animewatcher#13]
Anime in the Sub + Dub fragments are working fine, but when choosing the **Anime List** from toolbar menu
and clicking any anime, they don't work.

1- Dub + Sub = working fine
2 - searching anime and play it = working fine

3--> choosing the Anime list = not working (no episodes list found).

I think the links in the Json file in raw folder are wrong.

#Android 5.1 <22>

**Comment by balvinderz** [comment]
fixed it . thank you for reporting :) .
