### ISSUE TITLE
Does the anime need to be in the json file or does it download?

### ISSUE THREAD

**Issue by MoptopX** [balvinderz/animewatcher#3]
Is the json file just for the anime list function, will it still show new anime without needing to update it? Also, how do I generate the animelist.json file?

**Comment by balvinderz** [comment]
Yes the json file is just for the anime list function .  I m uploading the python program to generate animelist.json . you can check it out :) . The animelist.json file  does not show new anime. I update it every month .

**Comment by balvinderz** [comment]
[https://github.com/balvinderz/animewatcher/blob/master/generateanimelist.py](https://github.com/balvinderz/animewatcher/blob/master/generateanimelist.py)

**Comment by MoptopX** [comment]
Ok thanks, also can you make the anime page look better, sometimes the description falls off the image, looks ugly

**Comment by MoptopX** [comment]
That link to the regenerate thing is dead?

**Comment by balvinderz** [comment]
I removed everything

**Comment by MoptopX** [comment]
Why

**Comment by balvinderz** [comment]
Because you guys uploaded it on playstore or created your own modified app without giving me credits.

**Comment by MoptopX** [comment]
I didn't do anything?, I just cloned this like a few hours ago because I was trying to add Kitsu functions

**Comment by MoptopX** [comment]
Could I have that file please though?

**Comment by balvinderz** [comment]
u changed your whole backend . Why do u need it now ?

**Comment by MoptopX** [comment]
Huh, what are you talking about?

**Comment by MoptopX** [comment]
I just cloned this yesterday

**Comment by balvinderz** [comment]
You arr moptop32 from reddit right?

**Comment by MoptopX** [comment]
Nope, I don't use Reddit.

**Comment by MoptopX** [comment]
My name is Moptop because its an insult someone gave someone else in my hero academia. I thought it was a good username.

**Comment by balvinderz** [comment]
```
import requests
import json
from bs4 import *
baseurl ="https://www4.gogoanime.io/"
jsonlist=[]
for i in range(1,3):
    stringi=str(i)
    currenturl=baseurl+"anime-list.html?page="+stringi
    page=requests.get(currenturl)
    soup=BeautifulSoup(page.content,'html.parser')
    lis=soup.find('ul',class_='listing').find_all('li')
    for li in lis:
        x=BeautifulSoup(li.get('title'),'html.parser')
        imagelink=x.find('img').get('src')
        animelink=baseurl+li.find('a').get('href')
        title=x.find_all('div')[1].find('a').text
        #print(title)
        #print(animelink)
        anime={
            "anime" : {
                "Anime name" : title,
                "link" : animelink,
                "imagelink" : imagelink
                }
            }
        jsonlist.append(anime)
with open('animelist.json', 'w') as json_file:  
    json.dump(jsonlist, json_file)

```
This is a python file .

**Comment by MoptopX** [comment]
Thank you. When I finish kitsu integration and some other coolio features where do I send pull request though?

**Comment by balvinderz** [comment]
No need to send pull request. i m closing this repository

**Comment by MoptopX** [comment]
Oh ok, that is kind of sad, what happened?

**Comment by balvinderz** [comment]
A guy uploaded this app on playstore under his name .

**Comment by MoptopX** [comment]
I dont know how they got that app through even. Piracy apps are illegal on that store

**Comment by MoptopX** [comment]
Just report him for stealing the app, and report him for it being pirate app

**Comment by balvinderz** [comment]
I did

**Comment by faton-akiki** [comment]
I dont think its a coincidence having the same username moptop. I think you are the guy from AniStream, dont play dumb.

**Comment by MoptopX** [comment]
I do not use reddit or 4chan or anything

**Comment by MoptopX** [comment]
my username is a popular insult from a anime tv show

**Comment by balvinderz** [comment]
Ya he is . He even has a repository named anistream, i cant do anything so i gave him the python code :/

**Comment by faton-akiki** [comment]
Do you really think I am dumb. Look at your repositories. It says Anistream.

**Comment by MoptopX** [comment]
Thats the name of the app I want to make? I have no idea what you guys are talking about but I'm making my own app with this, its supposed to take stuff from anihub

**Comment by MoptopX** [comment]
Anistream-sync is a repo because I was planning to make a kitsu sync extension

**Comment by faton-akiki** [comment]
Hahahahahha what a coincidence😑

**Comment by MoptopX** [comment]
No idea what you are saying still, but I will most likely make my app public once it goes live, do I have permission to make it open source?

**Comment by faton-akiki** [comment]
https://app.anistream.xyz/ an app published today with the same name of your repository published by a guy named Moptop32. This says it all.

**Comment by MoptopX** [comment]
I have had my repository open for at least a month before today

**Comment by MoptopX** [comment]
And it has been completely empty for all the time because I gave up on making an extension that worked for more than one site.

**Comment by balvinderz** [comment]
Do whatever you want. I am not in the mood  of arguing. If you are blindly copying, it won't do anything good to you.

**Comment by MoptopX** [comment]
Ok whatever then
