### ISSUE TITLE
Source Code Needed Please Help Me Out ♥️

### ISSUE THREAD

**Issue by Rick0987** [balvinderz/animewatcher#6]
Hey There I Loved Your Work And I Know You Have Removed Your Source Code As Some Stealer Stole And Uploaded On PlayStore ( Got These Information From Previous Issues) But I Really Need Your Help. My College Has A Competition In Which We Have To Build Apps And Present It . I Just Wanted To Go Through The Source Code Of Your App To Know It's Working And Stuff. It'll Be Great If You Can Help Me Out. Eagerly Waiting For Your Response. ♥️

**Comment by Rick0987** [comment]
Please If Possible Drop Off The Source Code Via Email To trodri22@students.solano.edu Or hackeat0@gmail.com It's Fine If You Can't Share Out The Code I Understand But If Possible Just Guide Me Through Things I Have Been Working Day And Night To Develop A Web Scrapper Of Animes But At The End I'm Not Able To Succeed. You Are The Last Hope ♥️

**Comment by balvinderz** [comment]
i can give you code of scrapers if you want .I will not provide the app's source code.

**Comment by balvinderz** [comment]
Check your mail.

**Comment by Rick0987** [comment]
> i can give you code of scrapers if you want .I will not provide the app's source code.

Ya it's ok no worries i will try to develop things by looking at the files you gave or else I'll mail you if i need any help

**Comment by Rick0987** [comment]
Ya No Worries But If Possible Please Send The Complete App Source I Just Wanna Go Through The Working Of The App.  😅-------- Original message --------From: Balvinder Singh Gambhir <notifications@github.com>Date: Sat, 4 Jan, 2020, 10:06 AMTo: balvinderz/animewatcher <animewatcher@noreply.github.com>Cc: Rick0987 <hackeat0@gmail.com>, Author <author@noreply.github.com>Subject: Re: [balvinderz/animewatcher] Source Code Needed Please Help Me Out ♥️ (#6)i can give you code of scrapers if you want .I will not provide the app's source code.
