### ISSUE TITLE
App Crashes, When Reaching at the bottom of the List

### ISSUE THREAD

**Issue by MukanSharma** [balvinderz/animewatcher#7]
Scrolling through the Sub or Dub Section When We Reach at the End of the List then app Crashes.
While Debugging the App i found that error occurs on the AnimeDataAdapter.java on line 29,99.

Please Fix it ASAP. Love Your App though Keep it up.

**Comment by balvinderz** [comment]
will fix it when ihave time . :)

**Comment by balvinderz** [comment]
till then , can you make a video of the error and sent it to balvindersi2@gmail.com

**Comment by MukanSharma** [comment]
Fixed It ... Never Mind. 
But There is New error. :P
Half of the thumbnails are not showing up. Picasso is not getting their links. I saw in debug mode that links are loading but they are not reaching to Picasso.

**Comment by balvinderz** [comment]
I think you are modifying my app . Its working in the original repo.

**Comment by balvinderz** [comment]
That bug happens on some gogoanimes link . Use the link that I am using in the app . http://gogoanimee.io/

**Comment by MukanSharma** [comment]
I haven't modified your code. I just build it and used it for watching anime. 
i am using Google Pixel 3A API version 28.

**Comment by balvinderz** [comment]
Send your code at balvindersi2@gmail.com . I will take a look at it tomorrow

**Comment by MukanSharma** [comment]
code?? i m saying i havent changed anything in your code.. it is same as yours.

**Comment by balvinderz** [comment]
Send me your apk then

**Comment by MukanSharma** [comment]
Working Now.. Thanks For the Responses.!!

**Comment by MukanSharma** [comment]
https://youtu.be/Y50kLwiisU0

**Comment by balvinderz** [comment]
??

**Comment by MukanSharma** [comment]
Sorry message by mistakke
