### ISSUE TITLE
Videos Are Not Playing/Streaming

### ISSUE THREAD

**Issue by 72Daemon** [balvinderz/animewatcher#9]
Your app is loading the Episodes which is updated on GogoAnime But not Loading the Video. Your Previous build which you included in the Repo is working but not in the latest one.. May be they Changed the Source or something. Please fix it .. If you can.

thanks In advance :)

**Comment by balvinderz** [comment]
I fixed it today

**Comment by balvinderz** [comment]
Added new scrapers

**Comment by balvinderz** [comment]
sorry for the late fix . was busy
